# Generated by Django 2.2.4 on 2020-07-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Is ordered ?'),
        ),
    ]
